name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: XCode Test
      run: xcodebuild -project Dummy/Dummy.xcodeproj -scheme Dummy -destination "platform=iOS Simulator,name=iPhone XÊ€" test
